
title = "TOML Example"

[owner]
name = "Johnny Silverhand"
dob = 1988-11-16T07:32:00-08:00
password = "E9BD1C5B"

[my_cool_secrets]
things_i_like = ["Streamlit", "Music"]

[database]
enabled = true
ports = [ 8000, 8001, 8002 ]
data = [ ["delta", "phi"], [3.14] ]
temp_targets = { cpu = 79.5, case = 72.0 }

[servers]

[servers.alpha]
ip = "10.0.0.1"
role = "frontend"

[servers.beta]
ip = "10.0.0.2"
role = "backend"